"""add_academic_context_tables

Revision ID: bbe3696f456c
Revises: 
Create Date: 2026-02-20 22:51:36.458949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe3696f456c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_level',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('education_stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_academic_level_institution_name')
    )
    op.create_index(op.f('ix_academic_level_institution_id'), 'academic_level', ['institution_id'], unique=False)
    op.create_table('academic_year',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='academic_year_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_year_institution_id'), 'academic_year', ['institution_id'], unique=False)
    op.create_table('academic_period',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('snapshot_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_period_academic_year_id'), 'academic_period', ['academic_year_id'], unique=False)
    op.create_table('student_enrollment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('academic_level_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_level_id'], ['academic_level.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='uq_student_enrollment_student_year')
    )
    op.create_index(op.f('ix_student_enrollment_academic_level_id'), 'student_enrollment', ['academic_level_id'], unique=False)
    op.create_index(op.f('ix_student_enrollment_academic_year_id'), 'student_enrollment', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_student_enrollment_student_id'), 'student_enrollment', ['student_id'], unique=False)
    op.create_index(op.f('ix_competency_nucleus_id'), 'competency', ['nucleus_id'], unique=False)
    op.create_index(op.f('ix_indicator_stage_indicator_id'), 'indicator_stage', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_nucleus_subject_id'), 'nucleus', ['subject_id'], unique=False)
    op.create_index(op.f('ix_student_evidence_indicator_id'), 'student_evidence', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_student_evidence_indicator_stage_id'), 'student_evidence', ['indicator_stage_id'], unique=False)
    op.create_index(op.f('ix_student_evidence_student_id'), 'student_evidence', ['student_id'], unique=False)
    op.create_index(op.f('ix_subject_institution_id'), 'subject', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_institution_id'), table_name='subject')
    op.drop_index(op.f('ix_student_evidence_student_id'), table_name='student_evidence')
    op.drop_index(op.f('ix_student_evidence_indicator_stage_id'), table_name='student_evidence')
    op.drop_index(op.f('ix_student_evidence_indicator_id'), table_name='student_evidence')
    op.drop_index(op.f('ix_nucleus_subject_id'), table_name='nucleus')
    op.drop_index(op.f('ix_indicator_stage_indicator_id'), table_name='indicator_stage')
    op.drop_index(op.f('ix_competency_nucleus_id'), table_name='competency')
    op.drop_index(op.f('ix_student_enrollment_student_id'), table_name='student_enrollment')
    op.drop_index(op.f('ix_student_enrollment_academic_year_id'), table_name='student_enrollment')
    op.drop_index(op.f('ix_student_enrollment_academic_level_id'), table_name='student_enrollment')
    op.drop_table('student_enrollment')
    op.drop_index(op.f('ix_academic_period_academic_year_id'), table_name='academic_period')
    op.drop_table('academic_period')
    op.drop_index(op.f('ix_academic_year_institution_id'), table_name='academic_year')
    op.drop_table('academic_year')
    op.drop_index(op.f('ix_academic_level_institution_id'), table_name='academic_level')
    op.drop_table('academic_level')
    # ### end Alembic commands ###
